-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	ArrowLeft = "rbxassetid://7193741875",
	CommentBubble = "rbxassetid://7193938902",
	Delete = "rbxassetid://7193911951",
	Emojis = "rbxassetid://7194000666",
	Focus = "rbxassetid://7194058333",
	Reply = "rbxassetid://7193912115",
	Send = "rbxassetid://7193912190",
}